apiVersion: v1
kind: Service
metadata:
  name: hubspot-integration-service
spec:
  selector:
    app: hubspot-integration
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer